# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-02 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(blank=True, max_length=12, unique=True)),
                ('tracker_user', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='twitterdata',
            unique_together=set([('tracker_user', 'keyword')]),
        ),
    ]
